services:
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    container_name: discord-bot
    env_file:
      - .env
    restart: unless-stopped

  gitscrape:
    build:
      context: ./gitscrape
      dockerfile: Dockerfile
    container_name: gitscrape
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    
